# Generated by Django 4.1.12 on 2023-10-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_id',
        ),
        migrations.AddField(
            model_name='history',
            name='username',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
