# Generated by Django 4.2.6 on 2023-10-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='aprroved',
            field=models.BooleanField(default=True),
        ),
    ]
