# Generated by Django 4.2.6 on 2023-10-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_follower_aprroved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='aprroved',
            new_name='approved',
        ),
    ]
